/**
 * One-off bulk importer for the `agents` content collection.
 *
 *   npm run import:agents
 *
 * Reads import/agents.yaml, validates each entry against the same Zod shape
 * declared in src/content.config.ts, copies any matching screenshot from
 * import/shots/ into public/images/agents/, and writes a markdown file per
 * entry into src/content/agents/. Existing files are never overwritten.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync, copyFileSync } from 'node:fs';
import { dirname, extname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';
import { z } from 'zod';
import { slugify, stringifyMarkdown } from '../src/lib/frontmatter.ts';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const MANIFEST = join(ROOT, 'import', 'agents.yaml');
const SHOTS_DIR = join(ROOT, 'import', 'shots');
const CONTENT_DIR = join(ROOT, 'src', 'content', 'agents');
const PUBLIC_IMG_DIR = join(ROOT, 'public', 'images', 'agents');

// Mirror of the `agents` schema in src/content.config.ts. Keep these in sync.
// `hero` is generated by this script from `shot`, so we don't require it here.
// `shots` is an optional list of additional workflow screenshots that get
// appended to the body under a `## Workflows` section.
const shotEntrySchema = z.union([
  z.string(),
  z.object({ file: z.string(), caption: z.string().optional() }),
]);

const entrySchema = z.object({
  title: z.string().min(1),
  year: z.number().int(),
  summary: z.string().min(1),
  tags: z.array(z.string()).default([]),
  link: z.string().url().optional(),
  hero: z.string().optional(),
  order: z.number().default(0),
  draft: z.boolean().default(false),
  body: z.string().optional(),
  shot: z.string().optional(),
  shots: z.array(shotEntrySchema).optional(),
});

type Entry = z.infer<typeof entrySchema>;
type ShotEntry = z.infer<typeof shotEntrySchema>;

function loadManifest(): unknown[] {
  if (!existsSync(MANIFEST)) {
    throw new Error(`Manifest not found at ${MANIFEST}`);
  }
  const raw = readFileSync(MANIFEST, 'utf8');
  const parsed = yaml.load(raw);
  if (!Array.isArray(parsed)) {
    throw new Error('agents.yaml must be a top-level YAML array of entries');
  }
  return parsed;
}

function validateAll(rawEntries: unknown[]): Entry[] {
  const errors: string[] = [];
  const validated: Entry[] = [];
  rawEntries.forEach((raw, idx) => {
    const result = entrySchema.safeParse(raw);
    if (!result.success) {
      const label =
        raw && typeof raw === 'object' && 'title' in raw
          ? `"${(raw as { title: unknown }).title}"`
          : `index ${idx}`;
      for (const issue of result.error.issues) {
        errors.push(`  ${label} → ${issue.path.join('.') || '(root)'}: ${issue.message}`);
      }
      return;
    }
    validated.push(result.data);
  });
  if (errors.length > 0) {
    throw new Error(`Validation failed for ${errors.length} field(s):\n${errors.join('\n')}`);
  }
  return validated;
}

function resolveShot(shot: string | undefined, slug: string): { src: string; dest: string; rel: string } | null {
  if (!shot) return null;
  const src = join(SHOTS_DIR, shot);
  if (!existsSync(src)) {
    console.warn(`  ! shot "${shot}" not found in import/shots/ — skipping hero for ${slug}`);
    return null;
  }
  const ext = extname(shot).toLowerCase() || '.png';
  const destFile = `${slug}${ext}`;
  return {
    src,
    dest: join(PUBLIC_IMG_DIR, destFile),
    rel: `/images/agents/${destFile}`,
  };
}

function basenameWithoutExt(file: string): string {
  const ext = extname(file);
  return file.slice(0, file.length - ext.length);
}

function titleFromFilename(file: string): string {
  return basenameWithoutExt(file)
    .replace(/[-_]+/g, ' ')
    .replace(/\.flow$/i, '')
    .replace(/\b\w/g, (c) => c.toUpperCase())
    .trim();
}

/** Copy each extra shot into `public/images/agents/<slug>/` and return markdown for the body. */
function resolveExtraShots(shots: ShotEntry[] | undefined, slug: string): string {
  if (!shots || shots.length === 0) return '';
  const destDir = join(PUBLIC_IMG_DIR, slug);
  const blocks: string[] = [];
  let copied = 0;
  for (const raw of shots) {
    const file = typeof raw === 'string' ? raw : raw.file;
    const caption = typeof raw === 'string' ? titleFromFilename(file) : (raw.caption ?? titleFromFilename(file));
    const src = join(SHOTS_DIR, file);
    if (!existsSync(src)) {
      console.warn(`  ! shot "${file}" not found in import/shots/ — omitting from ${slug}`);
      continue;
    }
    mkdirSync(destDir, { recursive: true });
    const destFile = file.replace(/\s+/g, '-');
    copyFileSync(src, join(destDir, destFile));
    blocks.push(`![${caption}](/images/agents/${slug}/${destFile})\n\n*${caption}*`);
    copied += 1;
  }
  if (copied === 0) return '';
  return `\n\n## Workflows\n\n${blocks.join('\n\n')}\n`;
}

const FORCE = process.argv.includes('--force');

function writeEntry(entry: Entry): 'created' | 'skipped' | 'overwritten' {
  const slug = slugify(entry.title);
  const target = join(CONTENT_DIR, `${slug}.md`);
  const exists = existsSync(target);
  if (exists && !FORCE) {
    console.warn(`  - skip ${slug}.md (already exists, pass --force to overwrite)`);
    return 'skipped';
  }

  let hero = entry.hero;
  const shot = resolveShot(entry.shot, slug);
  if (shot) {
    mkdirSync(dirname(shot.dest), { recursive: true });
    copyFileSync(shot.src, shot.dest);
    hero = shot.rel;
  }

  const extraShotsMd = resolveExtraShots(entry.shots, slug);
  const body = (entry.body ?? '') + extraShotsMd;

  const data: Record<string, unknown> = {
    title: entry.title,
    year: entry.year,
    summary: entry.summary,
    tags: entry.tags,
    link: entry.link,
    hero,
    order: entry.order,
    draft: entry.draft,
  };

  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, stringifyMarkdown({ data, body }), 'utf8');
  console.log(`  ${exists ? '~' : '+'} ${slug}.md${hero ? ` (hero: ${hero})` : ''}`);
  return exists ? 'overwritten' : 'created';
}

function main() {
  const raw = loadManifest();
  const entries = validateAll(raw); // throws before any writes if invalid

  let created = 0;
  let skipped = 0;
  let overwritten = 0;
  let errors = 0;
  for (const entry of entries) {
    try {
      const result = writeEntry(entry);
      if (result === 'created') created += 1;
      else if (result === 'overwritten') overwritten += 1;
      else skipped += 1;
    } catch (err) {
      errors += 1;
      console.error(`  x ${entry.title}: ${(err as Error).message}`);
    }
  }
  console.log(`\nDone. ${created} created, ${overwritten} overwritten, ${skipped} skipped, ${errors} errors.`);
  if (errors > 0) process.exit(1);
}

try {
  main();
} catch (err) {
  console.error((err as Error).message);
  process.exit(1);
}
